modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
issueTrackerURL="https://github.com/caltinor" #optional
displayURL="https://github.com/caltinor" #optional
logoFile="" #optional
credits="Thanks to the MMD community." #optional
authors="Caltinor" #optional
license="ARR License"

[[mods]] #mandatory
modId="dicemccl" #mandatory
version="1.1b" #mandatory
displayName="Corrupeted Lands" #mandatory
#updateJSONURL=""
description='''
A SpookyJam Mod.
'''

[[dependencies.enderthing]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32.0.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.enderthing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"